### ISSUE TITLE
EVPLs should have a higher priority by default to also support an EPL in the same UNI

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#157]
This is for an use case in production that @jab1982 was mentioning, currently `mef_eline` supports an EVPL (vlan-based) and EPL (port-based) in the UNI. However, since the priority of the FlowMods installed via flow_manager isn't being set, they'd have the same priority, which can lead to undefined behavior when the switch will match a flow based on the OpenFlow spec. To support this use case, an initial idea is to have all EVPLs by default using a higher priority by default (500?) that could also be overwritten in the settings, that way regardless of the order an EPL and EVPL is installed, the EVPL will have higher priority flow entries.

**Comment by italovalcy** [comment]
@viniarck I think this is already possible through mef_eline's parameter `priority`. Check the sequence below:

1. Run kytos using the docker image `amlight/kytos:latest`
2. Starts mininet with a basic topology such as `tmux new-session -d -s mn mn --topo=linear,3 --controller=remote,ip=127.0.0.1`
3. Create an EPL between the NNI ports of switch 2, but using priority 1000 for instance.
```
curl -H 'Content-type: application/json' -X POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc -d '{"name": "my evc1", "dynamic_backup_path": true, "enabled": true, "uni_z": {"interface_id": "00:00:00:00:00:00:00:02:2"}, "uni_a": {"interface_id": "00:00:00:00:00:00:00:02:3"}, "priority": 1000}'
```
4. Create two EVPL to connect UNIs Switch1:1 and Switch2:1 using for instance priority 1500:
```
curl -H 'Content-type: application/json' -X POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc -d '{"name": "my evc1", "dynamic_backup_path": true, "enabled": true, "uni_z": {"tag": {"value": 198, "tag_type": 1}, "interface_id": "00:00:00:00:00:00:00:01:2"}, "uni_a": {"tag": {"value": 198, "tag_type": 1}, "interface_id": "00:00:00:00:00:00:00:01:1"}, "priority": 1500}'
curl -H 'Content-type: application/json' -X POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc -d '{"name": "my evc1", "dynamic_backup_path": true, "enabled": true, "uni_z": {"tag": {"value": 198, "tag_type": 1}, "interface_id": "00:00:00:00:00:00:00:02:2"}, "uni_a": {"tag": {"value": 198, "tag_type": 1}, "interface_id": "00:00:00:00:00:00:00:02:1"}, "priority": 1500}'
```
5. Test out connectivity between h1 and h2 (it will work despite the EPL being created first, due to the priorities) and also check the resulting flows.

This will give you what you need from the use case described above. I mean, we can work on having default values for certain types of EVCs, but maybe it is worth discussing again with @jab1982 to use what we already have (especially considering all the effort that this change may require)

**Comment by jab1982** [comment]
@italovalcy, thanks for your comment. Although it's good to know we have this flexibility now and we could use it in the short term, we need a solution that does not rely on users to set the flows' priorities. This will lead to issues in the future. I don't believe users should be allowed to manipulate the low level details of the southbound. In the future, we plan to open the API to the user community and it will lead to confusion. Also, the priority field in the EVC was suppose to describe administrative/business priority (gold, silver, best effort), not substrate priority. MEF E-Line should not accept that a EVPL has a lower priority than a EPL. It will be a lot of effort to fix this but we must do it. @viniarck , another issue to create/discuss is defining/documenting/enforcing the use of substrate priorities just as we did in the BGP Policy for BGP Local Preference.

**Comment by viniarck** [comment]
thanks @italovalcy and @jab1982, sounds like it'll need more refinement, so the original intention is that `priority` should be related to associating to a QoS queue, right? If it's related to QoS, in addition to refine the requirements, we might also need to try out `OFPAT_SET_QUEUE` (I haven't found unit tests on `python-openflow` covering this action yet), and map which queues would be in place and if they haven't been configured yet what the expected behavior would be, ignore the priority or reject, lots of details on this topic. I think we can further refine it on this issue #152 and also map the expected values for `priority` in the API, and on this current issue here, we only deal with fixing having higher priority flow entries for EVPLs by default, wdyt?

**Comment by viniarck** [comment]
Following up on this thread, I've collected more feedback from Italo and Jeronimo, it would be OK to introduce on settings two default priorities values for EPL and EVPL that should only be used if `sb_priority` isn't set in the request. The default value could be 1000 for `EVPL` and 500 for `EPL`, these variables could be called `EPL_SB_PRIORITY` and `EVPL_SB_PRIORITY` or something similar. We also need validations that `EVPL_SB_PRIORITY` > `EPL_SB_PRIORITY` during the NApp constructor.
