### ISSUE TITLE
ui is not sending the tag_value when tag_type is empty

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#215]
Hi,

The mef_eline UI is not sending the tag value when tag_type is empty. We've discussed in the past about setting the tag_type by default as 1 (even removing it from the user interface). Since the tag_type will always be "1" if the tag_value is used, it makes sense just to hide it (or present a dropdown with the default value as suggested in #139 - default and only value)

The current problem is when you insert a value for tag_value but leave tag_type empty, the UI does not send the tag in the request, and we end up successfully creating an EPL, even though the user requested an EVPL.

How to reproduce:
1. Using latest version of kytos, try to create an EVC on the web UI and provide the fields: Circuit Name = Test 123, First Endpoint = 00:00:00:00:00:00:00:01:1, tag value = 999, Last endpoint = 00:00:00:00:00:00:00:02:1, tag value = 999. (No tag_type should be provided! it should be left empty)
2. Submit the request (Request Circuit)

Expected behavior:

Option 1: the EVC be created with tag_type = 1 (which would be like a hidden default value)
Option 2: return an error to the user saying that tag_type is invalid (empty)

Actual behavior:

The evc is successfully created.

Trying to create the EVC from the command line without tag_type works fine:

```
# curl -X POST -H  'Content-type: application/json' http://67.17.206.201:8181/api/kytos/mef_eline/v2/evc/ -d '{"name":"Vlan_199_Novi01-23_Novi02-1","dynamic_backup_path":true,"enabled":true,"uni_a":{"interface_id":"00:00:00:00:00:00:00:01:23","tag":{"value":199}},"uni_z":{"interface_id":"00:00:00:00:00:00:00:02:1","tag":{"value":199}}}'
{"code":400,"description":"The request body contains invalid API data. 'tag_type' is a required property for field uni_a/tag.","name":"Bad Request"}
```

**Comment by viniarck** [comment]
Thanks for catching and reporting this @italovalcy
