### ISSUE TITLE
Include EVC's metadata on published CRUD events

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#223]
This is for augmenting certain mef_eline CRUD events like `kytos/mef_eline.created`, `kytos/mef_eline.deployed` and other CRUD related ones to also include a `metadata` key with the EVC metadata. 

`telemetry` will benefit from this since it'll subscribe to the events and knowing the metadata in the event simplifies some calls that would be needed otherwise.

**Comment by Alopalao** [comment]
Does this [PR](https://github.com/kytos-ng/mef_eline/pull/250) solve this issue too? Right now the event `kytos/mef_eline.created` is sending metadata as well.

**Comment by viniarck** [comment]
@Alopalao it does partly. Check out also issue #253 

We also need to cover these events, sending the entire evc dict representation, originally I mentioned only the `metadata` part but I believe other attrs such as `enabled` an so on is also needed, so sending the entire dict will provide everything that's needed:

```
kytos/mef_eline.updated
kytos/mef_eline.deleted
kytos/mef_eline.(redeployed_link_(up|down)|deployed)
```

For more information regarding `telemetry_int` spec and the integration with `mef_eline`, check out [EP031 blueprint](https://github.com/kytos-ng/kytos/blob/master/docs/blueprints/EP031.rst#v-events), the events section in this document will get a minor update, but you can get a general idea.
