### ISSUE TITLE
Provide bulk updates for metadata

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#225]
This is to cover https://github.com/kytos-ng/kytos/pull/279#discussion_r1015943926, 

Before implementing, the functionality it'll need to be refined to confirm it's aligned. Metadata bulk updates seem clear, but not filters for metadata we'll need to weigh the benefits, depending on the UIs and other clients it might be worth it otherwise it can be filtered at the runtime in an initial iteration since we know this collection won't be that large in practice.

**Comment by viniarck** [comment]
> Should the request changed to POST? Now that it will have a body in the request.

GET can also have a body, but let's simplify more here and stick with query params, let's also use MongoDB to it's full potential. We could potentially have `metadata_key` and `metadata_value` as query params, and then if a nested object like what `telemetry_int` needs to filter for is needed then we can use the "dot" object notation that is also compatible with mongo, for instance `"metadata_key=telemetry.enabled"` would try to filter the nested "enabled" key of a "telemetry" object. Wdyt? 

> For all the request, in case of error, is it preferable to make sure that every circuit_id sent exists before making changes to the databases or just process one by one?

Let's prioritize IO performance and minimize DB round trips, but let's keep the returned req status code coherently, and leverage MongoDB [`bulk_write` operations](https://www.mongodb.com/docs/manual/reference/method/db.collection.bulkWrite/#db.collection.bulkwrite--) - you can also check some examples we've been using [on flow_manager](https://github.com/kytos-ng/flow_manager/blob/master/controllers/__init__.py#L89-L98) - we won't use a transaction to simplify and avoid having to deal with transaction conflicts and other additional application locks that would be needed, and all existing objects will be updated even if one or few others don't exist, but when objects don't exist, then you let them dictate the status code of the request 404. Good thing is that `bulk_write` returns a counter of how many were modified so you always will be able to derive this efficiently. 

Also, @Alopalao on `POST and DELETE` endpoints, maybe instead of `evc_ids: List[str]` we can have `circuits_ids: List[str]`, wdyt? Looking into the current API the terminology circuit_id is already more widely used, so let's keep that consistent too.

**Comment by Alopalao** [comment]
For the `GET /v2/evc/` an instance for this call would be `/v2/evc?metadata_key=metadata.extra&metadata_value=data`. But would not be better with `/v2/evc?metadata.extra=data`, this way we are not limiting the request to one key metadata. I think it is possible with `request.args.keys()`.

**Comment by viniarck** [comment]
> For the `GET /v2/evc/` an instance for this call would be `/v2/evc?metadata_key=metadata.extra&metadata_value=data`. But would not be better with `/v2/evc?metadata.extra=data`, this way we are not limiting the request to one key metadata. I think it is possible with `request.args.keys()`.

Great idea, @Alopalao Yes, taking repeated metadata_key and metadata_value seems great. Regarding `/v2/evc?metadata.extra=data` I liked it, it's very convenient and to group them and parse would be easy too, since everything that starts with `"metadata."`
