### ISSUE TITLE
Updating an EVC from totally dynamic path to static primary and backup path may leave failover_path behind

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#235]
When we implemented the `failover_path` we restricted its applicability to "totally dynamic EVCs" (i.e., `dynamic_backup_path=True` and `primary_path=[]` and `backup_path=[]`), however when we update/patch an EVC and make it from a totally dynamic into a statically primary/backup path, the failover_path is left behind.

How to reproduce:
1. Create an EVC totally dynamic
2. Patch the EVC and provide the primary_path and backup_path

Expected behavior: the failover_path should be removed

Actual behavior: failover_path is left behind (btw, in an inconsistent state since the egress flows will not make more sense at that point)

**Comment by Alopalao** [comment]
I could not replicate this issue or maybe it has been fixed.
The steps I did, I created an EVC:
{
     "name": "my evc1",
     "dynamic_backup_path": true,
     "enabled": true,
     "uni_a": {
         "tag": {"value": 200, "tag_type": 1},
         "interface_id": "00:00:00:00:00:00:00:01:1"
         },
     "uni_z": {
         "tag": {"value": 100, "tag_type": 1},
         "interface_id": "00:00:00:00:00:00:00:03:1"
         }
 }
Then patch the EVC with:
{
    "primary_path": [
        {"endpoint_a": {"id": "00:00:00:00:00:00:00:01:3"},
         "endpoint_b": {"id": "00:00:00:00:00:00:00:02:2"}},
        {"endpoint_a": {"id": "00:00:00:00:00:00:00:02:3"},
         "endpoint_b": {"id": "00:00:00:00:00:00:00:03:2"}}
    ],
    "backup_path": [
        {"endpoint_a": {"id": "00:00:00:00:00:00:00:01:4"},
         "endpoint_b": {"id": "00:00:00:00:00:00:00:03:3"}}
    ]
}
But the failover has been deleted. Also, I tried with just "primary_path":
{
    "primary_path": [
        {"endpoint_a": {"id": "00:00:00:00:00:00:00:01:4"},
         "endpoint_b": {"id": "00:00:00:00:00:00:00:03:3"}}
    ]
}
Checked on OVS flows and every flow used by failover_path do no exist. @italovalcy please check if my example is incorrect.

**Comment by viniarck** [comment]
@italovalcy could you please double check if this is still happening? @Alopalao mentioned he couldn't replicate it back then. Thanks.

**Comment by viniarck** [comment]
Italo has just confirmed it's indirectly fixed. Aldo thanks for also trying to reproduce it. One less issue.
