### ISSUE TITLE
Missing parsing of flow_manager return codes

### ISSUE THREAD

**Issue by dgarc330** [kytos-ng/mef_eline#26]
Currently, the mef_eline napp is missing support for parsing the messages that it receives from the flow manager. Because of this, users can't really tell without looking at logs or elsewhere, if there is any problems with the flows or switches. 
This new feature will be a great tool in troubleshooting, and obtaining as much information as possible from the mef_eline.

**Comment by ajoaoff** [comment]
We have two scenarios here. In the first one, the EVC was created with a schedule, so it is not going to be deployed upon creation. In this scenario, there is no way to give a response to the user saying the deployment failed, as it is going to happen sometime in the future. That information can be logged and could also be sent to to user by e-mail or any other kind of message.
The second scenario is when the EVC has no schedule, so it will be deployed when created. In this case, it would be possible to tell the user if the deploy fails before sending the flows to the switches.
