### ISSUE TITLE
UI: after creating the EVC desired links is not cleared

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#263]
Hi,

All fields in the EVC creation form are cleared except the desired links for primary and secondary paths (probably also undesired links).

**Comment by italovalcy** [comment]
Other attributes that dont clear:
- SPF attribute
- SPF max path cost
- Min. flexible hits
- all of them

**Comment by viniarck** [comment]
Based on how things have evolved issue #283 will be shipped as an workaround on `2022.3.1`. 

This one here will be left for a next opportunity on `2023.1`
