### ISSUE TITLE
Add event to send cookie configuration

### ISSUE THREAD

**Issue by Alopalao** [kytos-ng/mef_eline#312]
Related to `kytos` issue [#186](https://github.com/kytos-ng/kytos/issues/186)
Add event `kytos/mef_eline.cookie` with content:
```
  "content": {
    "mef_eline": "0xaace2a57e8bfc642"
  }
```

**Comment by viniarck** [comment]
This is no longer needed, as we've been using `owner` and `table_group` on flow entries now.
