### ISSUE TITLE
docs: Include a link to the "Switch EVCs possibilities" spreadsheet on PR 258

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#335]
@Alopalao, can you include a link of the [Switch EVCs possibilities](https://docs.google.com/spreadsheets/d/1QNZJrB163oqgsaZAtEebsywmRlMlzQzhRNBNtC68iWE/edit#gid=1571705336) spreedsheet on PR https://github.com/kytos-ng/mef_eline/pull/258, and briefly explain what this spreadsheet shows? 

I'll mention this PR in the release notes highlighting that this spreadsheet is available to better understand which OpenFlow actions will be executed in case network operators want to use an asymmetric UNI configuration.

**Comment by Alopalao** [comment]
Added it.
