### ISSUE TITLE
EVC active status remains True when UNI is down

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#338]
Hi,

When an UNI is down, the EVC remains with `active=True`. Understing that the EVC is a service that relies on the UNIs, if the UNI is down, there is no service, so the EVC should have `active=False`.

It should be noticed though, that when a UNI is down, we don't need to recompute path and redeploy the EVC (or even send FlowMods)

**Comment by viniarck** [comment]
Side note: 

To consider down, to capture all the cases, if `interface.status != UP or interface.status_reason != {}`, following the same pattern compatible that logical interruptions have been evolved and implemented
