### ISSUE TITLE
bug: archived EVC is allowing its metadata to be updated

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#369]
bug: archived EVC is allowing its metadata to be updated

- `archived` represents a soft deletion, and general updates for instance, [aren't allowed either](https://github.com/kytos-ng/mef_eline/blob/master/main.py#L337), metadata of an EVC should follow the same logic, after all, it's an attribute of the underlying (archived) resource.

- Also, notice that the `self.circuits` is still keeping in memory deleted evcs, which can leave room for other bugs that are checking on `self.circuits` if the EVC exists, so whoever is fixing issue, take the opportunity to review that part too and assess any other potential issues. Historically, it made sense to keep `self.circuits` to also list archived EVCs, but since the `evcs` DB collection were introduced this is no longer necessary, so it's a technical debt that has been left behind.

How to reproduce:

- Create and then delete an EVC:

```
❯ echo '{ "name": "epl", "service_level": 7, "dynamic_backup_path": true, "uni_a": { "interface_id": "00:00:00:00:00:00:00:01:1" }, "uni_z": { "interface_id": "00:00:00:00:00:00:00:01:2"
 } }' | http POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/         
HTTP/1.1 201 Created
content-length: 31
content-type: application/json
date: Mon, 28 Aug 2023 02:31:30 GMT
server: uvicorn

{
    "circuit_id": "34241cc6e2f841"
}



❯ http DELETE http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/34241cc6e2f841
HTTP/1.1 200 OK
content-length: 45
content-type: application/json
date: Mon, 28 Aug 2023 02:32:08 GMT
server: uvicorn

{
    "response": "Circuit 34241cc6e2f841 removed"
}
```

- Try to updatethe metadata, notice it'll succeed, here I'm using the bulk endpoint

```
❯ echo '{ "some_key": "some_value", "circuit_ids": ["34241cc6e2f841"] }' | http POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/metadata
HTTP/1.1 201 Created
content-length: 22
content-type: application/json
date: Mon, 28 Aug 2023 02:32:34 GMT
server: uvicorn

"Operation successful"



❯ http http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/34241cc6e2f841 | jq .archived
true
```

cc'ing @Ktmi to add this to his radar under the `epic_mef_eline_enhancements`

**Comment by Ktmi** [comment]
Would it be possible, to instead make archiving take a snapshot of an EVC, and put that snapshot in a separate collection. That should in theory fix this issue, as all archived EVCs would be put into a collection of immutable objects. Additionally, we could use the same collection for tracking changes in EVCs over time, which I remember being something we wanted to do.

**Comment by viniarck** [comment]
@Ktmi, that's a good point. Indeed, supporting a richer EVC history has been asked. But, since it's a very large feature we do need to sort the requirements better first (let's see in a 2024 planning if it'll get prioritized), and a lot of it depends on how it'll be used, for instance, will network engineers only need the configuration part of the EVC at a time, or will they also want to keep track of potential dynamic things like the current_path at point in time? Anyway, I agree with you, having a separate collection for the history part makes a lot of sense to also avoid cluttering too much the `evcs` collection, specially depending on the requirements and how long we'll need to keep this history, and having a separate collection we'll make it easier to also leverage TTL indexes, if we need to auto delete them at some point, but let's continue this discussion once we have the rest of the requirements.

That said, in the meantime, for this iteration, let's only try to deliver the minimum part of not allowing metadata to be updated if an EVC is archived and also removed archived EVCs from `self.circuits`. Let me know if you're seeing any other simpler approach that still also solve this problem.
