### ISSUE TITLE
changing the primary path while the EVC is down can leave garbage flows on flow_manager

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#399]
Hi,

Same scenario as described on Issue #398, but if you manage to redeploy the EVC, you will notice that some flows were left behind  on s4:

```
root@72ffcb624ae6:/# for s in s1 s2 s3 s4; do echo $s; ovs-ofctl dump-flows $s; done
...
s4
 cookie=0xab00000000000004, duration=4025.421s, table=0, n_packets=160, n_bytes=6720, priority=50000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535
 cookie=0xac00000000000004, duration=4025.012s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:03 actions=CONTROLLER:65535
 cookie=0xaa23f4ff3f61ab42, duration=3792.100s, table=0, n_packets=0, n_bytes=0, priority=20000,in_port="s4-eth1",dl_vlan=100 actions=mod_vlan_vid:1,output:"s4-eth2"
 cookie=0xaa23f4ff3f61ab42, duration=3792.097s, table=0, n_packets=0, n_bytes=0, priority=20000,in_port="s4-eth2",dl_vlan=1 actions=strip_vlan,output:"s4-eth1"
```

Be advised of some discussions we are having on #394 regarding the empty current_path (if the current path were not empty, maybe this wouldn't happen -- however I'm not sure those two cases have to be handled together)

**Comment by Alopalao** [comment]
Was looking into this exact issue while working on PR [#415](https://github.com/kytos-ng/mef_eline/pull/415). Now flows are deleted after no other path was found. Important change, [code](https://github.com/kytos-ng/mef_eline/pull/415/commits/dd5d808b36f5a559d784e95dd29346cfbe4f85b1#diff-21bcbefe66b202d9442096930142c076c9aeef00956c3d7f33591d0ba295bc2fR1615)
