### ISSUE TITLE
EVC redeploys multiple times.

### ISSUE THREAD

**Issue by Alopalao** [kytos-ng/mef_eline#426]
Multiple redeployment happen at the start of kytos. To recreate this case:
Deploy this topology
```
From mininet.topo import Topo
class RingTopo(Topo):
    """Ring topology with three switches
    and one host connected to each switch"""

    def build(self):
        # Create two hosts
        h1 = self.addHost('h1', ip='0.0.0.0')
        h2 = self.addHost('h2', ip='0.0.0.0')
        h3 = self.addHost('h3', ip='0.0.0.0')
        h4 = self.addHost('h4', ip='0.0.0.0')

        # Create the switches
        s1 = self.addSwitch('s1')
        s2 = self.addSwitch('s2')
        s3 = self.addSwitch('s3')
        s4 = self.addSwitch('s4')

        # Add links between the switch and each host
        self.addLink(s1, h1)
        self.addLink(s2, h2)
        self.addLink(s3, h3)
        self.addLink(s4, h4)

        # Add links between the switchesz
        self.addLink(s1, s2)
        self.addLink(s1, s4)
        self.addLink(s2, s3)
        self.addLink(s3, s4)

topos = {"mytopo": (lambda: RingTopo())}
```
![min4](https://github.com/kytos-ng/mef_eline/assets/55767214/d72a25f9-12f6-4da8-b05e-6d6d30ef6788)

Create EVC, request body:
```
{
    "name": "EVC SW2",
    "dynamic_backup_path": true,
    "uni_a": {
        "tag": {"value": 200, "tag_type": 1},
        "interface_id": "00:00:00:00:00:00:00:01:2"
    },
    "uni_z": {
        "tag": {"value": 200, "tag_type": 1},
        "interface_id": "00:00:00:00:00:00:00:03:2"
    }
}
```
Restart Kytos.

**Comment by viniarck** [comment]
> From mininet.topo import Topo
> class RingTopo(Topo):
>     """Ring topology with three switches
>     and one host connected to each switch"""
> 
>     def build(self):
>         # Create two hosts
>         h1 = self.addHost('h1', ip='0.0.0.0')
>         h2 = self.addHost('h2', ip='0.0.0.0')
>         h3 = self.addHost('h3', ip='0.0.0.0')
>         h4 = self.addHost('h4', ip='0.0.0.0')
> 
>         # Create the switches
>         s1 = self.addSwitch('s1')
>         s2 = self.addSwitch('s2')
>         s3 = self.addSwitch('s3')
>         s4 = self.addSwitch('s4')
> 
>         # Add links between the switch and each host
>         self.addLink(s1, h1)
>         self.addLink(s2, h2)
>         self.addLink(s3, h3)
>         self.addLink(s4, h4)
> 
>         # Add links between the switchesz
>         self.addLink(s1, s2)
>         self.addLink(s1, s4)
>         self.addLink(s2, s3)
>         self.addLink(s3, s4)
> 
> topos = {"mytopo": (lambda: RingTopo())}

@Alopalao, I've also just explored it. Indeed it's a side effect of the issue #425. Due to that issue, we end up with links that actually don't exist, and then when a restart happens, then mef_eline will instantiate a non existing link, which in turn will be disabled, and as you pointed out will always result in the last item which is to try to redeploy again since it's a fully dynamic evc as a last resource. This was a good one to explore and confirm though. I'll go ahead and close this. If you end up seeing any other unwanted deployment in other cases, submit another issue, thanks.
