### ISSUE TITLE
UI: bug on displaying switch names and other metadata happening eventually

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#452]
Hi,

Not sure how to reproduce but this is happening pretty often on our production environment: eventually when loading the list of EVCs, the switch names will not show but the DPID instead. Same for when clicking to view the EVC information: eventually only datapath ID and interface IDs will be showed. If you refresh the page and reload it, the names are eventually loaded.

Here is one example:

![Screenshot 2024-04-09 at 17 10 36](https://github.com/kytos-ng/mef_eline/assets/168159/67915791-dbaa-487d-b1a7-6ca4bf04d52c)

**Comment by viniarck** [comment]
To try to reproduce try to add delay between client (front-end) and server. Request responses order.
