### ISSUE TITLE
UI: Bug when creating an EVC -- using the arrow keys plus enter leads to the EVC being prematurely requested

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#518]
Hi,

Using Kytos UI 2023.2.1 and trying to create a EVC presents a weird behavior not identified before: if you start typing the UNI interface and then use the arrow keys to select an interface then press Enter, this will lead to the EVC being prematurely requested. Some times even with the wrong data (before the autocomplete process it):

```
The request body contains invalid API data. 'sju_s02-eth7 - 00:00:00:00:00:24:00:02:7' is too long for field uni_z/interface_id.
```

![Screenshot 2024-10-01 at 14 27 26](https://github.com/user-attachments/assets/d2ba889d-5365-4fbe-aa92-e78bff1482b0)

**Comment by viniarck** [comment]
Thanks for catching this, Italo. I've just confirmed that on `master` it also happens:

![20241001_160417](https://github.com/user-attachments/assets/b111207d-d40e-4329-8c67-fd2bd1cdba44)

Let's see how can help to fix it and look into the `trevoreyre/autocomplete-vue` that you mentioned.

**Comment by viniarck** [comment]
Workaround:

During autocompletion if the user clicks instead of using keyboard arrow + enter, it works.

**Comment by italovalcy** [comment]
> Workaround:
> 
> During autocompletion if the user clicks instead of using keyboard arrow + enter, it works.

exactly. Forgot to mention this. Thanks for documenting it, Vinicius.
