### ISSUE TITLE
Kytos 2023.2 fail to report status of the EVC correctly

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#537]
Hi,

The EVC has an empty path but it is reporting as active and no log message about the EVC:

```
curl -X GET -u XXUSERXX -H 'Content-type: application/json' "https://xxxx/api/kytos/mef_eline/v2/evc/" > /tmp/evcs
> cat /tmp/evcs | jq -r '.["81f56a89c3164e"].current_path'
[]
> cat /tmp/evcs | jq -r '.["81f56a89c3164e"].active'
true
> cat /tmp/evcs | jq -r '.["81f56a89c3164e"].enabled'
true
> cat /tmp/evcs | jq -r '.["81f56a89c3164e"].primary_path|length'
4
> cat /tmp/evcs | jq -r '.["81f56a89c3164e"].backup_path|length'
4
```

**Comment by italovalcy** [comment]
Checked the EVC on the data-plane and it was really down

**Comment by viniarck** [comment]
That's definitely not good. @italovalcy lots of things going on, but later if you also have logs about the `81f56a89c3164e` EVC, if you can also post some events that can be helpful.

**Comment by Ktmi** [comment]
This technically ties back to #437, as this is one of the things that should be caught by consistency check.
