### ISSUE TITLE
UI: 2023.2 fail to create EVC with untagged VLAN string

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#541]
Hi,

IF you try to create an EVC on the UI for 2023.2, it won't say anything to the user but not let the user create the EVC. On the Safari browser console errors, you will see:

```
Console: SyntaxError: JSON Parse error: Unexpected identifier "untagged"

```

**Comment by jab1982** [comment]
@rmotitsuki , could you please run an assessment of this issue?

**Comment by viniarck** [comment]
@HeriLFIU will help out with this one, thanks, Heriberto. 

@rmotitsuki when you have availability later, if you can also review, that's appreciated.
