### ISSUE TITLE
Published and subscribed events missing from README

### ISSUE THREAD

**Issue by Auwate** [kytos-ng/mef_eline#546]
# Context

Almost all of the listed events (both published and subscribed) can by found in the utils.py, main.py, or models.py

## Published

There are published events that are not mentioned in the README file:

`kytos/mef_eline.redeployed_link_down` -> Found in the `handle_evc_affected_by_link_down` function

`kytos/mef_eline.error_redeploy_link_down` -> Found in the `handle_evc_affected_by_link_down` function

`kytos/mef_eline.cleanup_evcs_old_path` -> Found in the `handle_link_down`  function

`kytos/mef_eline.evcs_affected_by_link_down` -> Found in the `handle_link_down` function

`kytos/flow_manager.flows.install` -> Found in the `handle_link_down` function, which is then sent to the `send_flow_mods_event` function

`kytos/flow_manager.flows.deleted` -> Found in the `delete_circuit` function, which is then sent to the `send_flow_mods_event` function

`kytos/mef_eline.updated` -> Found in the `update` function

`kytos/mef_eline.redeployed_link_up` -> Found in the `handle_link_up` function

`kytos/mef_eline.undeployed` -> Found in the `remove` function

`kytos/mef_eline.deployed` -> Found in the `deploy` function

## Subscribed

Here are the subscribed events that are also not mentioned

`kytos/mef_eline.evc_affected_by_link_down`

`kytos/mef_eline.cleanup_evcs_old_path`

`kytos/mef_eline.redeployed_link_up`

`kytos/mef_eline.redeployed_link_down`

`kytos/mef_eline.deployed`

`.*.switch.interface.link_up`

`.*.switch.interface.link_down`

`.*.switch.interface.created`

`.*.switch.interface.deleted`

**Comment by viniarck** [comment]
Good finding @Auwate, indeed most here needs to be included. The only exception are non owning published events as we're discussing in other issues.

**Comment by Auwate** [comment]
Thanks @viniarck. So excluding the `.*.switch.interface.*` events, would you like me to create an MR and add these to the README file?
