### ISSUE TITLE
UI: When trying to create an EVC it says that description is undefined

### ISSUE THREAD

**Issue by HeriLFIU** [kytos-ng/mef_eline#596]
When you try to create an EVC it says that description is undefined.
![image](https://github.com/user-attachments/assets/3de3e2ac-3a94-4def-8086-8dc3d1482e47)

**Comment by viniarck** [comment]
@HeriLFIU, it resulted in a error 500 from the server that might be other issue in the back-end side (although other 500s can temporarily happen too), can you check in the Kytos console if you saw any other error? and see if this is deterministic too?

**Comment by HeriLFIU** [comment]
@viniarck I was able to recreate the issue. These were the steps I followed:
0. Exit Kytos if it was on
1. Exit Mininet and clean it
2. Turn off the docker containers and clear the volumes
3. Restart docker containers
4. Turn on Kytos
5. Create a linear topology, I used `sudo mn --controller=remote,ip=127.0.0.1,port=6653 --switch=ovsk,protocols=OpenFlow13 --topo linear,3`
6. I then created an EVC named Test as seen below:
![image](https://github.com/user-attachments/assets/d965ee54-8e2d-4274-8752-37f33e7ba45c)

**Comment by HeriLFIU** [comment]
When it occurs you get no logs, but it still creates the EVC.

**Comment by HeriLFIU** [comment]
It then only occurs again if you change both VLANs.

**Comment by HeriLFIU** [comment]
If you only change one EVC, you'll get the logging message of the previous attempt, or at least that's how it seems since you don't get the updated one.

**Comment by HeriLFIU** [comment]
If you wait a while and refresh it seems to fix itself.

**Comment by viniarck** [comment]
> When it occurs you get no logs, but it still creates the EVC.

Interesting @HeriLFIU, with the reproduction steps could you also please switch to the console network tab and see what's the content of the 500 response in this case?

**Comment by viniarck** [comment]
> @viniarck I was able to recreate the issue. These were the steps I followed: 0. Exit Kytos if it was on
> 
> 1. Exit Mininet and clean it
> 2. Turn off the docker containers and clear the volumes
> 3. Restart docker containers
> 4. Turn on Kytos
> 5. Create a linear topology, I used `sudo mn --controller=remote,ip=127.0.0.1,port=6653 --switch=ovsk,protocols=OpenFlow13 --topo linear,3`
> 6. I then created an EVC named Test as seen below:
>    ![image](https://private-user-images.githubusercontent.com/142065709/396654142-d965ee54-8e2d-4274-8752-37f33e7ba45c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjY2MzksIm5iZiI6MTczNDUyNjMzOSwicGF0aCI6Ii8xNDIwNjU3MDkvMzk2NjU0MTQyLWQ5NjVlZTU0LThlMmQtNDI3NC04NzUyLTM3ZjMzZTdiYTQ1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxMjUyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGIwNDgzNDk1NmY0MzI2NWFkYzZmYWFjNjE2NDcwZTBjMzFiZTgxOTkxZGIxMTU1YjA0MjdlYTcwZDQ1ZmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b9NBH88fpWH9oQuYtmm7QP7ugsQmCdLzmvRFdHwBekU)

Using `master` versions on kytos and NApps it's working for me:

![20241218_095949](https://github.com/user-attachments/assets/93e0585d-6441-4778-9f20-59fa0409071d)

Let's try to see the content of the response as I mentioned in the previous reply to see if it helps. We can also try to pair on it later. Thanks, Heriberto.

**Comment by HeriLFIU** [comment]
The issue was due to missing some new changes from Kytos. Once I had pulled them, it was resolved.
